id: spiral-gate
title: Spiral Gate
description: >
  Attune by spiraling counter-clockwise in time with the breath.
systems:
  motion:
    accel: 0.3
    maxSpeed: 1.8
    softWall: true
  gate:
    dir: 1        # 1 = CCW, -1 = CW
    friendliness: 0.9
    openThreshold: 0.75
    openSeconds: 2.5
  breath:
    swell: 1.0
    band:
      alphaBase: 0.2
      alphaGain: 0.4
    witness:
      auraRBase: 30
      auraRGain: 25
      auraABase: 0.15
      auraAGain: 0.35
  audio:
    enabled: true
    pad: "spiralPad"
    chime: "spiralChime"
debug:
  showWitnessVel: false
  showGateHalo: true